# Generated by Django 5.2.8 on 2025-12-03 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackerDefinition",
            fields=[
                (
                    "tracker_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "time_mode",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracker_definitions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["time_mode"], name="tracker_def_time_mo_db23dd_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tracker_def_created_7fd980_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "template_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("is_recurring", models.BooleanField(default=True)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("weight", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="core.trackerdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "task_templates",
                "ordering": ["tracker", "description"],
            },
        ),
        migrations.CreateModel(
            name="DayNote",
            fields=[
                (
                    "note_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="core.trackerdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "day_notes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TrackerInstance",
            fields=[
                (
                    "instance_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.trackerdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "tracker_instances",
                "ordering": ["-tracking_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "task_instance_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("MISSED", "Missed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.tasktemplate",
                    ),
                ),
                (
                    "tracker_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.trackerinstance",
                    ),
                ),
            ],
            options={
                "db_table": "task_instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["tracker", "category"], name="task_templa_tracker_5bf50c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="daynote",
            index=models.Index(
                fields=["tracker", "date"], name="day_notes_tracker_228953_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="daynote",
            unique_together={("tracker", "date")},
        ),
        migrations.AddIndex(
            model_name="trackerinstance",
            index=models.Index(
                fields=["tracker", "tracking_date"],
                name="tracker_ins_tracker_35eb3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackerinstance",
            index=models.Index(
                fields=["tracking_date"], name="tracker_ins_trackin_e87e23_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackerinstance",
            unique_together={("tracker", "tracking_date")},
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["tracker_instance", "status"],
                name="task_instan_tracker_7f408f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["template"], name="task_instan_templat_c28725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(fields=["status"], name="task_instan_status_13a6c1_idx"),
        ),
    ]
