# Generated by Django 5.2.9 on 2025-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltasktemplate',
            name='include_in_goal',
            field=models.BooleanField(default=True, help_text="Whether this task's points count towards the tracker goal"),
        ),
        migrations.AddField(
            model_name='historicaltasktemplate',
            name='points',
            field=models.IntegerField(default=1, help_text='Points awarded when task is completed (0 or more)'),
        ),
        migrations.AddField(
            model_name='historicaltrackerdefinition',
            name='goal_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', help_text='Period for goal reset (daily/weekly/custom)', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltrackerdefinition',
            name='goal_start_day',
            field=models.IntegerField(default=0, help_text='Start day for weekly goals (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='historicaltrackerdefinition',
            name='target_points',
            field=models.IntegerField(default=0, help_text='Target points for the goal (0 = no goal set)'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='include_in_goal',
            field=models.BooleanField(default=True, help_text="Whether this task's points count towards the tracker goal"),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='points',
            field=models.IntegerField(default=1, help_text='Points awarded when task is completed (0 or more)'),
        ),
        migrations.AddField(
            model_name='trackerdefinition',
            name='goal_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', help_text='Period for goal reset (daily/weekly/custom)', max_length=20),
        ),
        migrations.AddField(
            model_name='trackerdefinition',
            name='goal_start_day',
            field=models.IntegerField(default=0, help_text='Start day for weekly goals (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='trackerdefinition',
            name='target_points',
            field=models.IntegerField(default=0, help_text='Target points for the goal (0 = no goal set)'),
        ),
        migrations.AlterField(
            model_name='historicaltasktemplate',
            name='weight',
            field=models.IntegerField(default=1, help_text='Task priority/ordering weight (1-10)'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='weight',
            field=models.IntegerField(default=1, help_text='Task priority/ordering weight (1-10)'),
        ),
    ]
