# Generated by Django 5.2.8 on 2025-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taskinstance",
            name="task_instan_tracker_7f408f_idx",
        ),
        migrations.RemoveIndex(
            model_name="trackerinstance",
            name="tracker_ins_tracker_35eb3d_idx",
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["tracker_instance", "template", "status"],
                name="task_grid_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["status", "completed_at"], name="task_analytics"
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["template", "status"], name="task_template_status"
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["tracker_instance"], name="task_instan_tracker_e5e7bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["-created_at"], name="task_instan_created_629537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackerinstance",
            index=models.Index(
                fields=["tracker", "tracking_date", "status"],
                name="instance_date_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="trackerinstance",
            index=models.Index(
                fields=["tracker", "-tracking_date"], name="instance_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="trackerinstance",
            index=models.Index(fields=["status"], name="tracker_ins_status_d2732b_idx"),
        ),
    ]
