# Generated by Django 5.2.8 on 2025-12-04 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trackerdefinition",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trackers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="trackerdefinition",
            index=models.Index(
                fields=["user", "time_mode"], name="tracker_def_user_id_765b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackerdefinition",
            index=models.Index(
                fields=["user", "-created_at"], name="tracker_def_user_id_6085f0_idx"
            ),
        ),
    ]
