# Generated by Django 5.2.9 on 2025-12-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicaltasktemplate_include_in_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskinstance',
            name='first_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskinstance',
            name='last_status_change',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltaskinstance',
            name='snapshot_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltaskinstance',
            name='snapshot_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaltaskinstance',
            name='snapshot_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='first_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='snapshot_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='snapshot_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='snapshot_weight',
            field=models.IntegerField(default=1),
        ),
    ]
