# Generated by Django - Manual data migration
from django.db import migrations


def assign_trackers_to_first_user(apps, schema_editor):
    """
    Assign all existing trackers to the first user (or create one).
    Run this migration after adding the user field.
    """
    TrackerDefinition = apps.get_model('core', 'TrackerDefinition')
    User = apps.get_model('auth', 'User')
    
    # Get or create an admin user
    admin_user = User.objects.filter(is_superuser=True).first()
    
    if not admin_user:
        # If no superuser exists, use the first user
        admin_user = User.objects.first()
    
    if not admin_user:
        # If no users exist, create a default admin
        admin_user = User.objects.create_superuser(
            username='admin',
            email='admin@tracker.local',
            password='changeme123',  # User should change this!
        )
        print("Created default admin user: admin / changeme123")
    
    # Assign all trackers without a user to the admin
    orphan_trackers = TrackerDefinition.objects.filter(user__isnull=True)
    count = orphan_trackers.update(user=admin_user)
    
    if count > 0:
        print(f"Assigned {count} trackers to user: {admin_user.username}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_user_to_tracker'),
    ]

    operations = [
        migrations.RunPython(assign_trackers_to_first_user),
    ]
