# Generated by Django 5.2.9 on 2025-12-04 12:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_add_history_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daily_reminder_enabled', models.BooleanField(default=True)),
                ('daily_reminder_time', models.TimeField(blank=True, null=True)),
                ('weekly_review_enabled', models.BooleanField(default=True)),
                ('weekly_review_day', models.IntegerField(default=0)),
                ('default_view', models.CharField(choices=[('day', 'Day View'), ('week', 'Week View'), ('month', 'Month View')], default='week', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'System Default')], default='light', max_length=20)),
                ('show_completed_tasks', models.BooleanField(default=True)),
                ('streak_threshold', models.IntegerField(default=80)),
                ('consistency_window', models.IntegerField(default=7)),
                ('public_profile', models.BooleanField(default=False)),
                ('share_streaks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalTaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='core.goal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_mappings', to='core.tasktemplate')),
            ],
            options={
                'db_table': 'goal_task_mappings',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGoal',
            fields=[
                ('goal_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical goal',
                'verbose_name_plural': 'historical goals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_templates', to='core.tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='core.tasktemplate')),
            ],
            options={
                'db_table': 'task_template_tags',
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('relation_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('from_entity_type', models.CharField(choices=[('task', 'Task Instance'), ('template', 'Task Template'), ('tracker', 'Tracker'), ('note', 'Day Note'), ('goal', 'Goal')], max_length=20)),
                ('from_entity_id', models.CharField(max_length=36)),
                ('to_entity_type', models.CharField(choices=[('task', 'Task Instance'), ('template', 'Task Template'), ('tracker', 'Tracker'), ('note', 'Day Note'), ('goal', 'Goal')], max_length=20)),
                ('to_entity_id', models.CharField(max_length=36)),
                ('relation_type', models.CharField(choices=[('done_on', 'Done On'), ('blocked_by', 'Blocked By'), ('related_to', 'Related To'), ('depends_on', 'Depends On'), ('inspired_by', 'Inspired By'), ('replaces', 'Replaces')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entity_relations',
                'indexes': [models.Index(fields=['from_entity_type', 'from_entity_id'], name='entity_rela_from_en_0f420a_idx'), models.Index(fields=['to_entity_type', 'to_entity_id'], name='entity_rela_to_enti_7fec69_idx'), models.Index(fields=['relation_type'], name='entity_rela_relatio_7011da_idx'), models.Index(fields=['user', 'relation_type'], name='entity_rela_user_id_c6121e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_user_id_49fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', '-created_at'], name='goals_user_id_475d55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goaltaskmapping',
            unique_together={('goal', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplatetag',
            unique_together={('template', 'tag')},
        ),
    ]
