# Generated by Django 5.2.9 on 2025-12-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_tags_goals_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('habit', 'Habit'), ('achievement', 'Achievement'), ('project', 'Project')], default='habit', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='icon',
            field=models.CharField(blank=True, default='🎯', max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='core.trackerdefinition'),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='goal_type',
            field=models.CharField(choices=[('habit', 'Habit'), ('achievement', 'Achievement'), ('project', 'Project')], default='habit', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='icon',
            field=models.CharField(blank=True, default='🎯', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='tracker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trackerdefinition'),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltasktemplate',
            name='time_of_day',
            field=models.CharField(choices=[('anytime', 'Any Time'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='anytime', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltrackerdefinition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='time_of_day',
            field=models.CharField(choices=[('anytime', 'Any Time'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='anytime', max_length=20),
        ),
        migrations.AddField(
            model_name='trackerdefinition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='week_start',
            field=models.IntegerField(default=0),
        ),
    ]
